apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-vaultk8s-job
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/bevel-vault-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    metadata:
      name: carrier-vaultk8s-job
      namespace: carrier-net
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      role: vault-role
      address: http://127.0.0.1:8200
      authpath: devcarrier-net-auth
      policy: vault-crypto-carrier-net-carrier-ro
      policydata: "\n{\n  \"policy\": \"\\npath \\\"secretsv2/*\\\" {\n    \\ncapabilities = [\\\"list\\\"]\\n\n  }\n  \\npath \\\"secretsv2/data/crypto/ordererOrganizations/*\\\" {\n    \\ncapabilities = [\\\"deny\\\"]\\n\n  }\n  \\npath \\\"secretsv2/data/credentials/carrier-net/*\\\" {\n    \\ncapabilities = [\\\"list\\\", \\\"read\\\", \\\"create\\\", \\\"update\\\"]\\n\n  }\n  \\npath \\\"secretsv2/data/crypto/peerOrganizations\\\" {\n    \\ncapabilities = [\\\"deny\\\"]\\n\n  }\n  \\npath \\\"secretsv2/data/crypto/peerOrganizations/carrier-net/*\\\" {\n    \\ncapabilities = [\\\"list\\\", \\\"read\\\", \\\"create\\\", \\\"update\\\"]\\n\n  }\"\n}"
      secret_path: secretsv2
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://test-bevel-integra-dns-elwgnmdn.hcp.eastus.azmk8s.io:443
    
    rbac:
      create: True

    serviceAccount:
      create: True
      name: vault-auth
