apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: warehouse-net-ca
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: warehouse-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server  
  values:
    metadata:
      namespace: warehouse-net
      images:
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
        ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
 
    server:
      name: ca
      tlsstatus: true
      admin: warehouse-admin 
  
    storage:
      storageclassname: warehouse-azure-storageclass
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://18.219.111.164:8200
      authpath: devwarehouse-net-auth
      secretcert: secretsv2/data/crypto/peerOrganizations/warehouse-net/ca?ca.warehouse-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/warehouse-net/ca?warehouse-net-CA.key
      secretadminpass: secretsv2/data/credentials/warehouse-net/ca/warehouse?user
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          clusteripport: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: test-bevel-integra-dns-elwgnmdn.hcp.eastus.azmk8s.io
